parameters:
  - name: templateRepository
    default: Azure Pipelines
  - name: poolName
    default: Azure Pipelines
  - name: configuration
    default: CI
  - name: createPackage
    type: boolean
    default: false
  - name: packageName
    default: ''
  - name: synchronizeDatabase
    type: boolean
    default: false
  - name: deployReports
    type: boolean
    default: false
  - name: useNuGetPipeline
    type: boolean
    default: true

stages:
  - ${{ if eq(parameters['useNuGetPipeline'], true) }}:
    - stage: buildXppCode
      displayName: "Build X++ code"
      jobs:
        - template: /Templates/Jobs/BuildPackagesNuget.yaml@${{ parameters.templateRepository }}
          parameters:
            poolName:             ${{ parameters.poolName }}
            configuration:        ${{ parameters.configuration }}
            createPackage:        ${{ parameters.createPackage }}
            packageName:          ${{ parameters.packageName }}
  - ${{ else }}:
    - stage: buildXppCode
      displayName: "Build X++ code"
      jobs:
        - template: /Templates/Jobs/BuildPackagesHostedAgent.yaml@${{ parameters.templateRepository }}
          parameters:
            poolName:             ${{ parameters.poolName }}
            configuration:        ${{ parameters.configuration }}
            createPackage:        ${{ parameters.createPackage }}
            synchronizeDatabase:  ${{ parameters.synchronizeDatabase }}
            deployReports:        ${{ parameters.deployReports }}
            packageName:          ${{ parameters.packageName }}