parameters:
  - name: assetUploadStep
    default: uploadModels
  
stages: 
  - stage: testVariables
    dependsOn: ${{ parameters.assetUploadStep }}
    jobs:
      - job: showOutput
        pool:
          name: 'Azure Pipelines'
          vmImage: 'windows-2019'
        variables:
          - name: LocalLCSAssetId
            value: stageDependencies.${{ parameters.assetUploadStep }}.PostProcessVariables.outputs['printvar.lcsAssetId']
        steps:
          - checkout: none 
          - pwsh: |
              echo "LCSAssetId is $(LocalLCSAssetId)"