parameters:
  - name: configuration
  - name: buildConfiguration
    default: 'debug'
  - name: createPackage
    default: false 
  - name: packageName

jobs:
- job: BuildXppPackageNuGet
  displayName: 'Build X++ Package (Microsoft agent)'
  pool:
    name: Azure Pipelines
    vmImage: 'windows-2022'
    demands: [visualstudio, msbuild]
  variables:
    App1Package:        'Microsoft.Dynamics.AX.Application1.DevALM.BuildXpp'
    App2Package:        'Microsoft.Dynamics.AX.Application2.DevALM.BuildXpp'
    AppSuitePackage:    'Microsoft.Dynamics.AX.ApplicationSuite.DevALM.BuildXpp'
    PlatPackage:        'Microsoft.Dynamics.AX.Platform.DevALM.BuildXpp'
    ToolsPackage:       'Microsoft.Dynamics.AX.Platform.CompilerPackage'

    NugetsPath:         '$(Pipeline.Workspace)\NuGets'
    NugetConfigsPath:   '$(Build.SourcesDirectory)\.pipeline\NuGet'
    MetadataPath:       '$(Build.SourcesDirectory)\Metadata'
    xppModelSolution:   '$(Build.SourcesDirectory)\.pipeline\BuildProject\BuildProject.sln'

  steps:
    - task: NuGetCommand@2
      displayName: 'Install FinOps NuGet packages'
      inputs:
        command: custom
        arguments: 'install -Noninteractive $(NugetConfigsPath)\packages.config  -ConfigFile $(NugetConfigsPath)\nuget.config -Verbosity Detailed  -ExcludeVersion  -OutputDirectory "$(NugetsPath)"'

    - task: XppUpdateModelVersion@0
      displayName: 'Update Model Version'
      inputs:
        XppSourcePath: '$(MetadataPath)'
        VersionNumber: '$(Build.BuildNumber)'

    - task: VSBuild@1
      displayName: 'Build X++ Model'
      inputs:
        configuration: ${{ parameters.buildConfiguration }}
        solution: '$(xppModelSolution)'
        msbuildArgs: '/restore /p:BuildTasksDirectory="$(NugetsPath)\$(ToolsPackage)\DevAlm" /p:MetadataDirectory="$(MetadataPath)" /p:FrameworkDirectory="$(NuGetsPath)\$(ToolsPackage)" /p:ReferenceFolder="$(NuGetsPath)\$(PlatPackage)\ref\net40;$(NuGetsPath)\$(App1Package)\ref\net40;$(NuGetsPath)\$(App2Package)\ref\net40;$(NuGetsPath)\$(AppSuitePackage)\ref\net40;$(MetadataPath);$(Build.BinariesDirectory)" /p:ReferencePath="$(NuGetsPath)\$(ToolsPackage)" /p:OutputPath="$(Agent.BuildDirectory)\Bin"'

    - ${{ if eq(parameters['createPackage'], true) }}:
      - task: PowerShell@2
        displayName: Move ISV solutions to compiler output folder
        inputs:
          targetType: inline
          script: |
            # Get all subdirectories in the source directory
            $SubDirectories = Get-ChildItem -Path $(Build.SourcesDirectory)\Metadata -Directory

            foreach ($SubDir in $SubDirectories) {
                # Check if the bin folder exists in the root of the current subdirectory
                $BinFolderPath = Join-Path -Path $SubDir.FullName -ChildPath "bin"
                if (Test-Path -Path $BinFolderPath) {
                    # Check if the bin folder contains a file ending with _ModelInfo.md
                    $ModelInfoFile = Get-ChildItem -Path $BinFolderPath -File | Where-Object { $_.Name -like "*_ModelInfo.md" }
                    if ($ModelInfoFile) {
                        # Move the entire folder to the target directory
                        $DestinationPath = Join-Path -Path $(Agent.BuildDirectory)\Bin -ChildPath $SubDir.Name
                        Move-Item -Path $SubDir.FullName -Destination $DestinationPath
                        Write-Host "Moved folder: $($SubDir.Name)"
                    } else {
                        Write-Host "No _ModelInfo.md file found in bin folder of $($SubDir.Name)"
                    }
                } else {
                    Write-Host "bin folder not found in $($SubDir.Name)"
                }
            }

      - task: XppCreatePackage@2
        displayName: 'Create Deployable Package'
        inputs:
          XppBinariesSearch:
          XppToolsPath: $(NuGetsPath)\$(ToolsPackage)
          XppBinariesPath:  $(Agent.BuildDirectory)\Bin
          CreateRegularPackage: true
          DeployablePackagePath: '$(Build.ArtifactStagingDirectory)\DeployablePackage\${{ parameters.packageName }}.zip'
          CreateCloudPackage: true
          CloudPackageOutputLocation: '$(Build.ArtifactStagingDirectory)\CloudPackage'

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: BuildArtifacts

      - publish: $(Build.SourcesDirectory)\Licenses\
        artifact: Licenses
