parameters:
  - name: configuration
  - name: buildConfiguration
    default: 'debug'
  - name: createPackage
    default: false 
  - name: packageName

jobs:
  - job: BuildXppPackageNuGet
    displayName: 'Build X++ Package (Microsoft agent)'
    pool:
      name: Azure Pipelines
      vmImage: 'windows-2022'
      demands: [visualstudio, msbuild]
    variables:
      App1Package:        'Microsoft.Dynamics.AX.Application1.DevALM.BuildXpp'
      App2Package:        'Microsoft.Dynamics.AX.Application2.DevALM.BuildXpp'
      AppSuitePackage:    'Microsoft.Dynamics.AX.ApplicationSuite.DevALM.BuildXpp'
      PlatPackage:        'Microsoft.Dynamics.AX.Platform.DevALM.BuildXpp'
      ToolsPackage:       'Microsoft.Dynamics.AX.Platform.CompilerPackage'

      NugetsPath:         '$(Pipeline.Workspace)\NuGets'
      NugetConfigsPath:   '$(Build.SourcesDirectory)\.pipeline\NuGet'
      MetadataPath:       '$(Build.SourcesDirectory)\Metadata'
      xppModelSolution:   '$(Build.SourcesDirectory)\.pipeline\BuildProject\BuildProject.sln'

    steps:
    - task: PowerShell@2
      displayName: 'Initialize D365FO.Tools and variables'
      inputs:
        targetType: inline
        script: |
          Write-Output "##vso[task.setvariable variable=licenseExists]$((Test-Path "$(Build.SourcesDirectory)\Licenses\*.txt"))"

    - task: NuGetCommand@2
      displayName: 'Install FinOps NuGet packages'
      inputs:
        command: custom
        arguments: 'install -Noninteractive $(NugetConfigsPath)\packages.config  -ConfigFile $(NugetConfigsPath)\nuget.config -Verbosity Detailed  -ExcludeVersion  -OutputDirectory "$(NugetsPath)"'

    - task: XppUpdateModelVersion@0
      displayName: 'Update Model Version'
      inputs:
        XppSourcePath: '$(MetadataPath)'
        VersionNumber: '$(Build.BuildNumber)'

    - task: VSBuild@1
      displayName: 'Build X++ Model'
      inputs:
        configuration: ${{ parameters.buildConfiguration }}
        solution: '$(xppModelSolution)'
        msbuildArgs: '/restore /p:BuildTasksDirectory="$(NugetsPath)\$(ToolsPackage)\DevAlm" /p:MetadataDirectory="$(MetadataPath)" /p:FrameworkDirectory="$(NuGetsPath)\$(ToolsPackage)" /p:ReferenceFolder="$(NuGetsPath)\$(PlatPackage)\ref\net40;$(NuGetsPath)\$(App1Package)\ref\net40;$(NuGetsPath)\$(App2Package)\ref\net40;$(NuGetsPath)\$(AppSuitePackage)\ref\net40;$(MetadataPath);$(Build.BinariesDirectory)" /p:ReferencePath="$(NuGetsPath)\$(ToolsPackage)" /p:OutputDirectory="$(Build.BinariesDirectory)"'

    - ${{ if eq(parameters['createPackage'], true) }}:
      - task: CopyFiles@2
        displayName: 'Copy X++ Compile Log Files for Artifact Publishing'
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)"
          Contents: |
            **\Dynamics.AX.*.xppc.*
            **\Dynamics.AX.*.labelc.*
            **\Dynamics.AX.*.reportsc.*
          TargetFolder: '$(Build.ArtifactStagingDirectory)\Logs\'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Compile logs'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\Logs\'
          ArtifactName: 'CompileLogs'

      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 3.3.0'
        inputs:
          versionSpec: 3.3.0

      - task: XppCreatePackage@0
        displayName: 'Create Deployable Package'
        inputs:
          XppToolsPath: $(NuGetsPath)\$(ToolsPackage)
          XppBinariesPath: $(Build.BinariesDirectory)
          XppBinariesSearch: |
            '*'
            $(Build.SourcesDirectory)\Metadata\*
          DeployablePackagePath: '$(Build.ArtifactStagingDirectory)\$(Build.ArtifactStagingDirectory)\${{ parameters.packageName }}'

      - task: XppAddLicenseToPackage@0
        displayName: 'Add Licenses to Deployable Package'
        condition: and(succeeded(), eq(variables['licenseExists'], true))
        inputs:
          LicenseFilePaths: '$(Build.SourcesDirectory)\License\*.txt'
          DeployablePackagePath: '$(Build.ArtifactStagingDirectory)\$(Build.ArtifactStagingDirectory)\${{ parameters.packageName }}'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: DeployablePackage'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\${{ parameters.packageName }}'
          ArtifactName: 'DeployablePackage'
          publishLocation: 'Container'