parameters:
  - name: packageName
  - name: poolName

jobs:  
  - job: BuildPostProcess
    displayName: 'Post processing of build artifacts' 
    pool:
      ${{ if eq(parameters['poolName'], 'Azure Pipelines') }}:
        name: 'Azure Pipelines'
        vmImage: 'windows-2022'
        demands: 
          - msbuild
          - visualstudio
      ${{ else }}:
        name: '${{ parameters.poolName }}'
        demands: 
          - msbuild
          - visualstudio
    - download: current
      artifact: BuildArtifacts
    - download: current
      artifact: Licenses
    - task: PowerShell@2
      displayName: 'Check for availabile licenses in license folder'
      inputs:
        targetType: inline
        script: |
          Write-Output "##vso[task.setvariable variable=licenseExists]$((Test-Path "$(Build.SourcesDirectory)\Licenses\*.txt"))"
    - task: XppAddLicenseToPackage@1
      displayName: 'Add Licenses to Deployable Package'
      condition: and(succeeded(), eq(variables['licenseExists'], true))
      inputs:
        PackageType: 0
        LicenseFilePaths: '$(Build.SourcesDirectory)\Licenses\*.txt'
        DeployablePackagePath: '$(Build.ArtifactStagingDirectory)\DeployablePackage\${{ parameters.packageName }}.zip'
    - ${{ each model in split(parameters['licensedModels'], ';')}}:
      - task: XppAddLicenseToPackage@1
        displayName: 'Add Licenses to Cloud Package'
        condition: and(succeeded(), eq(variables['licenseExists'], true))
        inputs:
          PackageType: 1
          ModelName: ${{ model }}
          LicenseFilePaths: '$(Build.SourcesDirectory)\Licenses\*.txt'
          DeployablePackagePath: '$(Build.ArtifactStagingDirectory)\CloudPackage'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: DeployablePackage'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\DeployablePackage\${{ parameters.packageName }}.zip'
        ArtifactName: 'DeployablePackage'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: CloudPackage'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\CloudPackage'
        ArtifactName: 'CloudPackage'
        publishLocation: 'Container'