parameters:
  - name: lcsServiceConnectionName
  - name: lcsProjectId
  - name: packageName
  - name: poolName

jobs:  
  - job: UploadDeployablePackage
    dependsOn: ${{ parameters.DependsOn }}
    displayName: 'Upload deployable package to LCS' 
    pool:
      pool:
      name: Azure Pipelines
      vmImage: 'windows-2022'
      demands: [visualstudio, msbuild]
    
    steps:
    - checkout: none

    - download: current
      artifact: BuildArtifacts

    - task: LCSAssetUpload@2
      inputs:
        serviceConnectionName: ${{ parameters.lcsServiceConnectionName }}
        projectId: ${{ parameters.lcsProjectId }}
        assetType: '10'
        assetPath: $(Pipeline.Workspace)\BuildArtifacts\DeployablePackage\${{ parameters.packageName }}.zip

    - task: PowerShell@2
      displayName: 'Output LCS asset id'
      name: lcsAssetIdStep
      inputs:
        targetType: inline
        script: |
          Write-Output "##vso[task.setvariable variable=lcsAssetId;isOutput=true]$(("variables['FileAssetId']"))"
      
